# This file is autogenerated
import threading
import ctypes
import os
from pyautd3.native_methods.autd3capi_def import ModulationPtr, ResultModulation, SamplingConfiguration


class Singleton(type):
    _instances = {}  # type: ignore
    _lock = threading.Lock()

    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            with cls._lock:
                if cls not in cls._instances:
                    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
        return cls._instances[cls]


class NativeMethods(metaclass=Singleton):

    def init_dll(self, bin_location: str, bin_prefix: str, bin_ext: str):
        try:
            self.dll = ctypes.CDLL(os.path.join(bin_location, f'{bin_prefix}autd3capi_modulation_audio_file{bin_ext}'))
        except Exception:
            return

        self.dll.AUTDModulationWav.argtypes = [ctypes.c_char_p, SamplingConfiguration]  # type: ignore 
        self.dll.AUTDModulationWav.restype = ResultModulation

        self.dll.AUTDModulationWavIsDefault.argtypes = [ModulationPtr]  # type: ignore 
        self.dll.AUTDModulationWavIsDefault.restype = ctypes.c_bool

        self.dll.AUTDModulationRawPCM.argtypes = [ctypes.c_char_p, ctypes.c_uint32, SamplingConfiguration]  # type: ignore 
        self.dll.AUTDModulationRawPCM.restype = ResultModulation

        self.dll.AUTDModulationRawPCMIsDefault.argtypes = [ModulationPtr]  # type: ignore 
        self.dll.AUTDModulationRawPCMIsDefault.restype = ctypes.c_bool

    def modulation_wav(self, path: bytes, config: SamplingConfiguration) -> ResultModulation:
        return self.dll.AUTDModulationWav(path, config)

    def modulation_wav_is_default(self, wav: ModulationPtr) -> ctypes.c_bool:
        return self.dll.AUTDModulationWavIsDefault(wav)

    def modulation_raw_pcm(self, path: bytes, sample_rate: int, config: SamplingConfiguration) -> ResultModulation:
        return self.dll.AUTDModulationRawPCM(path, sample_rate, config)

    def modulation_raw_pcm_is_default(self, rawpcm: ModulationPtr) -> ctypes.c_bool:
        return self.dll.AUTDModulationRawPCMIsDefault(rawpcm)
