# This file is autogenerated
import threading
import ctypes
import os
from pyautd3.native_methods.structs import Vector3, Quaternion, FfiFuture, LocalFfiFuture
from enum import IntEnum


class Status(IntEnum):
    Error = 0
    Lost = 1
    StateChanged = 2

    @classmethod
    def from_param(cls, obj):
        return int(obj)  # pragma: no cover


class ProcessPriority(IntEnum):
    Idle = 0
    BelowNormal = 1
    Normal = 2
    AboveNormal = 3
    High = 4
    Realtime = 5

    @classmethod
    def from_param(cls, obj):
        return int(obj)  # pragma: no cover


class TimerStrategy(IntEnum):
    SpinSleep = 0
    StdSleep = 1
    SpinWait = 2

    @classmethod
    def from_param(cls, obj):
        return int(obj)  # pragma: no cover


