name: Coverage

on:
  push:
    branches:
      - 'develop'

jobs:
  check-src:
    runs-on: ubuntu-latest
    name: check if src files changed
    outputs:
      status: ${{ steps.changed-files.outputs.modified_files }}
    steps:
      - uses: actions/checkout@v3
      - uses: tj-actions/changed-files@v40
        id: changed-files
        with:
          files: |
            .github/workflows/coverage.yml
            setup.cfg.template
            MANIFEST.in
            ./pyautd3/*.py
            ./pyautd3/**/*.py
            ./tests/*.py
            ./tests/**/*.py

  coverage:
    needs: check-src
    if: needs.check-src.outputs.status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install packaging
        run: |
          python3 -m pip install -U packaging requests

      - name: install cuda
        shell: bash
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update
          sudo apt-get -y install cuda-nvcc-12-2 libcublas-dev-12-2 libcusolver-dev-12-2
          echo "/usr/local/cuda/bin" >> $GITHUB_PATH

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: latest
          cache: true

      - name: Generate code coverage for python
        run: |
          python3 -m pip install -U pytest pytest-asyncio pytest-cov
          python3 -m pip install -U numpy matplotlib
          python3 x.py cov --cov_report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
